apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: capc-webhook-service
spec:
  selector: {}
  ports:
    -
      name: webhooks
      protocol: TCP
      port: 443
      targetPort: 9443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: capc-webhook-service
subsets:
  -
    addresses:
      -
        ip: ${MY_IP}
    ports:
      -
        port: 9443
        name: webhooks
