# TODO actually turn this into a template. Right now it is a finalized/filled version.
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: cluster1
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: CloudStackCluster
    name: cluster1
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: cluster1-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: CloudStackCluster
metadata:
  name: cluster1
spec:
  # This is an ACS Public IP address at which the K8s server will be exposed.
  controlPlaneEndpoint:
    host: 192.168.1.14
    port: 6443
  network: GuestNet1
  zone: zone1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: cluster1-control-plane
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      imageRepository: k8s.gcr.io
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: "cloudstack:///'{{ ds.meta_data.instance_id }}'"
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: "cloudstack:///'{{ ds.meta_data.instance_id }}'"
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: CloudStackMachineTemplate
      name: cluster1-control-plane
  replicas: 1
  version: v1.21.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: CloudStackMachineTemplate
metadata:
  name: cluster1-control-plane
spec:
  template:
    spec:
      offering: Large Instance
      sshKey: CAPCKeyPair6
      template: ubuntu20
      details:
        memoryOvercommitRatio: "1.2"
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  name: cluster1-md-0
spec:
  clusterName: cluster1
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
          name: cluster1-md-0
      clusterName: cluster1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: CloudStackMachineTemplate
        name: cluster1-md-0
      version: v1.21.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: CloudStackMachineTemplate
metadata:
  name: cluster1-md-0
spec:
  template:
    spec:
      offering: Large Instance
      sshKey: CAPCKeyPair6
      template: ubuntu20
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: cluster1-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: cloudstack:///'{{ ds.meta_data.instance_id }}'
          name: '{{ local_hostname }}'
